[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = []
# Skip PHP detection
onlyIncludeFiles = ["package.json", "package-lock.json"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
]

[start]
cmd = "npx serve play.pokemonshowdown.com -l 8080 --single"
